CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL
);

CREATE TABLE calendars (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    theme VARCHAR(100) DEFAULT NULL,
    color VARCHAR(7) DEFAULT NULL,
    bg_image VARCHAR(255) DEFAULT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE calendar_days (
    id INT AUTO_INCREMENT PRIMARY KEY,
    day INT NOT NULL,
    is_unlocked BOOLEAN DEFAULT FALSE
);
